### ISSUE TITLE
[CR-H] 홀 좌석 점유 api 개발

### ISSUE THREAD

**Issue by shindh12** [STOS-INC/concert-reservation#23]
## task
- [x] 좌석 점유 api
- [x] 좌석 점유 취소 api
- [x] 좌석 점유 검증 로직 추가 (DB 상태 + 레디스 상태)

## description
일정 기간(5분) 동안 예매 완료 상태가 되지 않는 케이스 상태 관리 로직도 포함
(배치, 레디스 락, 선택시간 검증 등)

## functional requirements
 - 좌석을 임시로 점유한다.
 - 좌석 임시 점유를 취소한다.

## non functional requirements
 - 점유 요청의 동시성을 보장해야 한다.
 - 임시 점유 실패 시 exception 처리를 해줘야 한다.
