### ISSUE TITLE
[CR-C] 예외 처리 공통로직 개발

### ISSUE THREAD

**Issue by ppurxx** [STOS-INC/concert-reservation#9]
## dependency module
common

## task
- [x] error module 추가
- [x] exception module 추가
- [x] exception model 추가

## description
오류 케이스 정의 및 핸들러 등등 고려

## non functional requirements
- 각 애플리케이션에 맞게 커스텀 할 수 있도록 확장성을 고려한다.
